services:
  ubuntu-nfs:
    build:
      context: .
      dockerfile: Dockerfile
    image: sagarparker/nfs_oyster:latest
    init: true
    network_mode: host
    volumes:
      - /app/decrypted:/app/nfs/