services:
  app:
    container_name: governance
    network_mode: host
    image: jerryandspike/governance_enclave:v1.0
    ports:
      - "3001:3001"
    env_file:
      - /init-params/.env
    restart: unless-stopped