version: "3.9"

services:
  app:
    container_name: governance
    build:
      context: .
    image: rust-app:latest
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped